# ruff: noqa: E501, S101

import re
import unittest
import xml.etree.ElementTree as ET
from fractions import Fraction
from typing import Any

import musicxml.xmlelement.xmlelement as mxl

from homr.music_xml_generator import (
    SymbolChord,
    XmlGeneratorArguments,
    find_division_and_time_signature_nominator,
    generate_xml,
    rebalance_measure_voices,
)
from homr.transformer.vocabulary import EncodedSymbol
from training.transformer.training_vocabulary import (
    read_token_lines,
)


def _onsets(xml: Any) -> list[tuple[str, str, float]]:
    """(staff, pitch with octave, onset in quarter notes) for every note of the first measure."""
    root = ET.fromstring(xml.to_string())  # noqa: S314 - generated by the test itself
    part = root.find("part")
    assert part is not None
    divisions = int(part.findtext("measure/attributes/divisions", "1"))
    measure = part.find("measure")
    assert measure is not None
    time, onset, result = 0, 0, []
    for element in measure:
        if element.tag == "backup":
            time -= int(element.findtext("duration", "0"))
        elif element.tag == "forward":
            time += int(element.findtext("duration", "0"))
        elif element.tag == "note":
            if element.find("chord") is None:
                onset = time
                time += int(element.findtext("duration", "0"))
            pitch = element.find("pitch")
            name = (
                "rest"
                if pitch is None
                else pitch.findtext("step", "") + pitch.findtext("octave", "")
            )
            result.append((element.findtext("staff", "1"), name, onset / divisions))
    return sorted(result)


class TestMusicXmlGenerator(unittest.TestCase):
    """
    MusicXML testing is mostly covered by training/validate_music_xml_conversion.py
    This script requires that the data sets are downloaded and converted and uses
    the data sets to check that back and forth conversion works.
    """

    def test_chord_with_different_duratons(self) -> None:
        tabi_measure_18_upper = """clef_G2 . . . . upper
keySignature_4 . . . . .
timeSignature/8 . . . . .
note_4. G3 # _ _ upper &note_4. C4 # _ _ upper&note_16 E4 # _ _ upper
note_16 F4 # _ _ upper
note_4 E4 # _ _ upper
note_8 E4 # _ _ upper
note_8 C4 # _ _ upper
note_8 D4 # _ _ upper
barline . . . . ."""
        tokens = read_token_lines(tabi_measure_18_upper.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        actual = self._xml_to_str(xml)
        expected = """XMLScorePartwise([XMLWork([XMLWorkTitle()]),
XMLPart([XMLMeasure([XMLAttributes([XMLDivisions(value: 4)]),
XMLAttributes([XMLKey([XMLFifths(value: 4)]),
XMLTime([XMLBeats(value: 6),
XMLBeatType(value: 8)]),
XMLClef([XMLSign(value: G),
XMLLine(value: 2)])]),
XMLNote([XMLPitch([XMLStep(value: E)]),
XMLDuration(value: 1),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLBackup([XMLDuration(value: 1)]),
XMLNote([XMLPitch([XMLStep(value: G)]),
XMLDuration(value: 6),
XMLVoice(value: 2),
XMLDot(),
XMLStaff(value: 1),
XMLNotations()]),
XMLNote([XMLChord(),
XMLPitch([XMLStep(value: C)]),
XMLDuration(value: 6),
XMLVoice(value: 2),
XMLDot(),
XMLStaff(value: 1),
XMLNotations()]),
XMLBackup([XMLDuration(value: 5)]),
XMLNote([XMLPitch([XMLStep(value: F)]),
XMLDuration(value: 1),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLNote([XMLPitch([XMLStep(value: E)]),
XMLDuration(value: 4),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLNote([XMLPitch([XMLStep(value: E)]),
XMLDuration(value: 2),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLNote([XMLPitch([XMLStep(value: C)]),
XMLDuration(value: 2),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLNote([XMLPitch([XMLStep(value: D)]),
XMLDuration(value: 2),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()])])])])"""
        self.assertEqual(self._norm_expected(expected), actual)

    def test_grand_staff_generation(self) -> None:
        grandstaff = """clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower
keySignature_1 . . . . .
timeSignature/4 . . . . .
note_1 G4 _ _ _ upper&note_1 A3 # _ _ upper&rest_2 _ _ _ _ upper&note_4 G3 _ _ _ lower
rest_4 _ _ _ _ lower
note_2 E4 _ _ _ upper&note_2 C2 _ _ _ lower
barline . . . . ."""
        tokens = read_token_lines(grandstaff.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        actual = self._xml_to_str(xml)
        expected = """XMLScorePartwise([XMLWork([XMLWorkTitle()]),
XMLPart([XMLMeasure([XMLAttributes([XMLDivisions(value: 1)]),
XMLAttributes([XMLKey([XMLFifths(value: 1)]),
XMLTime([XMLBeats(value: 4),
XMLBeatType(value: 4)]),
XMLClef([XMLSign(value: G),
XMLLine(value: 2)]),
XMLClef([XMLSign(value: F),
XMLLine(value: 4)])]),
XMLNote([XMLRest(),
XMLDuration(value: 2),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLBackup([XMLDuration(value: 2)]),
XMLNote([XMLPitch([XMLStep(value: G)]),
XMLDuration(value: 4),
XMLVoice(value: 2),
XMLStaff(value: 1),
XMLNotations()]),
XMLNote([XMLChord(),
XMLPitch([XMLStep(value: A)]),
XMLDuration(value: 4),
XMLVoice(value: 2),
XMLStaff(value: 1),
XMLNotations()]),
XMLBackup([XMLDuration(value: 4)]),
XMLNote([XMLPitch([XMLStep(value: G)]),
XMLDuration(value: 1),
XMLVoice(value: 5),
XMLStaff(value: 2),
XMLNotations()]),
XMLNote([XMLRest(),
XMLDuration(value: 1),
XMLVoice(value: 5),
XMLStaff(value: 2),
XMLNotations()]),
XMLNote([XMLPitch([XMLStep(value: E)]),
XMLDuration(value: 2),
XMLVoice(value: 1),
XMLStaff(value: 1),
XMLNotations()]),
XMLBackup([XMLDuration(value: 2)]),
XMLNote([XMLPitch([XMLStep(value: C)]),
XMLDuration(value: 2),
XMLVoice(value: 5),
XMLStaff(value: 2),
XMLNotations()])])])])"""
        self.assertEqual(self._norm_expected(expected), actual)

    def test_begin_chord_with_standalone_rests(self) -> None:
        """
        If the lower position consists of a standalone rest then start the
        chord with this. That fixes an issue where the upper position
        consists of tuplets because in that case backups must not be used.

        See tabi.jpg measure 9 for an example.
        """
        chord = SymbolChord(
            [
                EncodedSymbol("note_12", position="upper"),
                EncodedSymbol("note_12", position="upper"),
                EncodedSymbol("rest_8", position="lower"),
            ]
        )
        first, second = chord.into_positions()

        self.assertEqual(first.symbols, [EncodedSymbol("rest_8", position="lower")])
        self.assertEqual(
            second.symbols,
            [
                EncodedSymbol("note_12", position="upper"),
                EncodedSymbol("note_12", position="upper"),
            ],
        )

    def test_rebalance_measure_voices_assigns_stable_voices_per_staff(self) -> None:
        measure = mxl.XMLMeasure()

        note1 = self._build_test_note(duration=4, staff=1, voice=1)
        measure.add_child(note1)
        measure.add_child(self._build_test_backup(duration=4))

        # Overlaps note1, so this must move to voice 2.
        note2 = self._build_test_note(duration=2, staff=1, voice=1)
        measure.add_child(note2)

        # Starts later but still overlaps with note1, reusing voice 2.
        note3 = self._build_test_note(duration=2, staff=1, voice=1)
        measure.add_child(note3)

        # Chord tone sharing note3's timing; should get the same voice as note3.
        note4 = self._build_test_note(duration=2, staff=1, voice=1, is_chord=True)
        measure.add_child(note4)

        measure.add_child(self._build_test_backup(duration=4))
        note5 = self._build_test_note(duration=4, staff=2, voice=1)
        measure.add_child(note5)
        measure.add_child(self._build_test_backup(duration=4))

        # Overlaps note5 on staff 2.
        note6 = self._build_test_note(duration=2, staff=2, voice=1)
        measure.add_child(note6)

        rebalance_measure_voices(measure)

        # Same-start events are processed by (start, end), so shorter durations
        # receive lower local voice numbers first.
        self.assertEqual(self._read_note_voice(note1), "2")
        self.assertEqual(self._read_note_voice(note2), "1")
        self.assertEqual(self._read_note_voice(note3), "1")
        self.assertEqual(self._read_note_voice(note4), "1")
        self.assertEqual(self._read_note_voice(note5), "6")
        self.assertEqual(self._read_note_voice(note6), "5")

    def test_next_group_starts_when_the_earliest_sounding_note_ends(self) -> None:
        """
        Tokens tell which notes start together, not when each group starts. Here the left
        hand's quarter note E3 starts under the right hand's quarter note C5, so the right
        hand's D5 starts when C5 ends (beat 1), while E3 is still sounding. Advancing by the
        shortest note of the group just written would put D5 at beat 1.5 instead.
        """
        hands_moving_independently = """clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower
keySignature_0 . . . . .
timeSignature/4 . . . . .
note_4 C5 _ _ _ upper&note_8 C3 _ _ _ lower
note_4 E3 _ _ _ lower
note_4 D5 _ _ _ upper
note_8 G3 _ _ _ lower
note_2 E5 _ _ _ upper&note_2 C3 _ _ _ lower
barline . . . . ."""
        tokens = read_token_lines(hands_moving_independently.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        self.assertEqual(
            _onsets(xml),
            sorted(
                [
                    ("1", "C5", 0.0),
                    ("1", "D5", 1.0),
                    ("1", "E5", 2.0),
                    ("2", "C3", 0.0),
                    ("2", "E3", 0.5),
                    ("2", "G3", 1.5),
                    ("2", "C3", 2.0),
                ]
            ),
        )

    def test_independent_hands_in_elijah_measure(self) -> None:
        """
        Measure 6 of the Elijah page from upstream issue #142: the right hand plays a
        quarter chord and dotted rhythms while the left hand holds A2 and moves in eighths
        and quarters. Every note must start on its beat, so that no staff runs past the end
        of the 4/4 measure. Upstream writes the held A2 as a second lower voice
        (``lower2``); this vocabulary has one lower position, so it shares ``lower``.
        """
        elijah_measure_6 = """clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower
keySignature_-4 . . . . .
timeSignature/4 . . . . .
note_4 A4 b _ _ upper&note_4 E4 b _ _ upper&note_4 C4 _ _ _ upper&note_2 A2 b _ _ lower&note_8 A2 b _ _ lower
note_4 A3 b _ _ lower
note_8. A4 b _ _ upper&note_8. E4 b _ _ upper&note_8. C4 _ _ _ upper
note_8 A3 b _ _ lower
note_16 C5 _ _ _ upper&note_16 A4 b _ _ upper&note_16 E4 b _ _ upper
note_8. C5 _ _ _ upper&note_8. A4 b _ _ upper&note_8. G4 b _ _ upper&note_8. E4 b _ _ upper&note_8 A2 b _ _ lower
note_4 C4 _ _ _ lower&note_4 A3 b _ _ lower
note_16 E5 b _ _ upper&note_16 A4 b _ _ upper&note_16 G4 b _ _ upper
note_8. E5 b _ _ upper&note_8. A4 b _ _ upper&note_8. G4 b _ _ upper
note_8 E4 b _ _ lower&note_8 C4 _ _ _ lower&note_8 A3 b _ _ lower
note_16 E5 b _ _ upper&note_16 A4 b _ _ upper&note_16 G4 b _ _ upper
barline . . . . ."""
        tokens = read_token_lines(elijah_measure_6.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        onsets = _onsets(xml)
        upper = sorted({onset for staff, _, onset in onsets if staff == "1"})
        lower = sorted({onset for staff, _, onset in onsets if staff == "2"})
        self.assertEqual(upper, [0.0, 1.0, 1.75, 2.0, 2.75, 3.0, 3.75])
        self.assertEqual(lower, [0.0, 0.5, 1.5, 2.0, 2.5, 3.5])

    def test_grace_notes_take_no_time(self) -> None:
        """A group of only grace notes must not move later notes (the next note stays on beat 1)."""
        with_grace_note = """clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower
keySignature_0 . . . . .
timeSignature/4 . . . . .
note_4 C5 _ _ _ upper&note_2 C3 _ _ _ lower
note_8G D5 _ _ _ upper
note_4 E5 _ _ _ upper
note_2 F5 _ _ _ upper&note_2 G2 _ _ _ lower
barline . . . . ."""
        tokens = read_token_lines(with_grace_note.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        by_pitch = {name: onset for _, name, onset in _onsets(xml)}
        self.assertEqual(by_pitch["E5"], 1.0)
        self.assertEqual(by_pitch["F5"], 2.0)
        self.assertEqual(by_pitch["G2"], 2.0)

    def test_rest_under_a_held_note_starts_when_the_note_ends(self) -> None:
        """
        Super Mario Bros Ground Theme, measure 19, as the transformer reads it. The bass
        quarter A2 is still sounding when the treble's quarter chord starts on the second
        eighth, so the bass eighth rest starts when A2 ends (beat 1), not when the treble
        chord does (beat 1.5). The late start left a gap that renderers filled with an
        extra rest in each staff and overfilled the 2/2 measure.
        """
        ground_theme_measure_19 = """clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower
keySignature_0 . . . . .
timeSignature/2 . . . . .
note_8 C5 _ _ _ upper&note_8 A4 b _ _ upper&note_4 A2 b _ _ lower
note_4 C5 _ _ _ upper&note_4 A4 b _ _ upper
rest_8 _ _ _ _ lower
note_8 C5 _ _ _ upper&note_8 A4 b _ _ upper&note_8 E3 b _ _ lower
rest_8 _ _ _ _ upper&rest_4 _ _ _ _ lower
note_8 C5 _ _ _ upper&note_8 A4 b _ _ upper
note_4 D5 _ _ _ upper&note_4 B4 b _ _ upper&note_4 A3 b _ _ lower
barline . . . . ."""
        tokens = read_token_lines(ground_theme_measure_19.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        onsets = _onsets(xml)
        self.assertIn(("2", "rest", 1.0), onsets)
        self.assertIn(("2", "E3", 1.5), onsets)
        self.assertIn(("2", "A3", 3.0), onsets)
        self.assertIn(("1", "D5", 3.0), onsets)
        self.assertEqual(max(onset for _, _, onset in onsets), 3.0)

    def test_divisions_represent_notes_that_are_not_the_shortest_of_their_group(self) -> None:
        """
        The triplet quarter is never the shortest note of its group, yet its length and
        the backup after it must be whole numbers of divisions. Counting only each group's
        shortest note left the triplet's denominator out of the LCM, which truncated
        durations to zero.
        """
        groups = [
            SymbolChord(
                [
                    EncodedSymbol("note_6", "C5", position="upper"),
                    EncodedSymbol("note_8", "C3", position="lower"),
                ]
            ),
            SymbolChord([EncodedSymbol("note_8", "E3", position="lower")]),
            SymbolChord([EncodedSymbol("barline")]),
        ]
        division, _ = find_division_and_time_signature_nominator(groups)
        self.assertEqual(division % 3, 0)

    def test_time_signature_counts_held_notes_once(self) -> None:
        """
        The time signature token carries only the beat type; the beat count comes from
        the typical bar length. A bar in which the bass holds a quarter under the treble's
        quarter chord is one 2/2 bar, not 9/8 of one.
        """
        staggered_bar = [
            [
                EncodedSymbol("note_8", "C5", position="upper"),
                EncodedSymbol("note_4", "A2", position="lower"),
            ],
            [EncodedSymbol("note_4", "C5", position="upper")],
            [EncodedSymbol("rest_8", "_", position="lower")],
            [
                EncodedSymbol("note_8", "C5", position="upper"),
                EncodedSymbol("note_8", "E3", position="lower"),
            ],
            [
                EncodedSymbol("rest_8", "_", position="upper"),
                EncodedSymbol("rest_4", "_", position="lower"),
            ],
            [EncodedSymbol("note_8", "C5", position="upper")],
            [
                EncodedSymbol("note_4", "D5", position="upper"),
                EncodedSymbol("note_4", "A3", position="lower"),
            ],
            [EncodedSymbol("barline")],
        ]
        groups = [SymbolChord(symbols) for symbols in staggered_bar * 3]
        _, nominator = find_division_and_time_signature_nominator(groups)
        self.assertEqual(nominator, Fraction(1))

    def test_triplets_over_eighths_start_on_their_beats(self) -> None:
        """
        A triplet quarter beside an eighth: the next eighth starts under the held triplet,
        and every duration and backup is a whole number of divisions.
        """
        triplet_over_eighths = """clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower
keySignature_0 . . . . .
timeSignature/4 . . . . .
note_6 C5 _ _ _ upper&note_8 C3 _ _ _ lower
note_8 E3 _ _ _ lower
note_6 D5 _ _ _ upper
note_4 G3 _ _ _ lower
note_6 E5 _ _ _ upper
note_2 F5 _ _ _ upper&note_2 C3 _ _ _ lower
barline . . . . ."""
        tokens = read_token_lines(triplet_over_eighths.splitlines())
        xml = generate_xml(XmlGeneratorArguments(), [tokens], "")
        root = ET.fromstring(xml.to_string())  # noqa: S314 - generated by the test itself
        divisions = int(root.findtext("part/measure/attributes/divisions", "0"))
        self.assertEqual(divisions % 3, 0)
        durations = [int(d.text or "0") for d in root.iter("duration")]
        self.assertTrue(all(d > 0 for d in durations))
        by_pitch = {name: onset for _, name, onset in _onsets(xml)}
        self.assertAlmostEqual(by_pitch["E3"], 0.5)
        self.assertAlmostEqual(by_pitch["D5"], 2 / 3)
        self.assertAlmostEqual(by_pitch["F5"], 2.0)

    def _norm_expected(self, expected: str) -> str:
        norm = expected.replace("\n", "")
        norm = re.sub(r",\s+", ",", norm)
        norm = re.sub(r"\[\s+", "[", norm)
        return norm

    def _xml_to_str(self, xml: Any) -> str:
        def recurse(node_or_list: Any) -> str:
            if isinstance(node_or_list, list):
                return (
                    "["
                    + ",".join(recurse(child) for child in node_or_list if child is not None)
                    + "]"
                )

            node = node_or_list
            name = node.__class__.__name__

            ignore_nodes = (
                "XMLAlter",
                "XMLOctave",
                "XMLType",
                "XMLPartList",
                "XMLDefaults",
                "XMLIdentification",
                "XMLEncoding",
                "XMLSoftware",
                "XMLStaves",
                "XMLPartSymbol",
            )

            if name in ignore_nodes:
                return ""
            value = getattr(node, "value_", None)

            if hasattr(node, "children"):
                children = node.children
            elif hasattr(node, "get_children"):
                children = node.get_children()
            else:
                children = []

            child_strs = [recurse(child) for child in children if child is not None]
            child_strs = [child for child in child_strs if child != ""]

            parts = []
            if value is not None and value != "":
                parts.append(f"value: {value}")
            if child_strs:
                parts.append(f"[{','.join(child_strs)}]")

            if parts:
                return f"{name}({','.join(parts)})"
            else:
                return f"{name}()"

        return recurse(xml)

    def _build_test_note(
        self, duration: int, staff: int, voice: int, is_chord: bool = False
    ) -> mxl.XMLNote:
        note = mxl.XMLNote()
        if is_chord:
            note.add_child(mxl.XMLChord())
        note.add_child(mxl.XMLDuration(value_=duration))
        note.add_child(mxl.XMLStaff(value_=staff))
        note.add_child(mxl.XMLVoice(value_=str(voice)))
        return note

    def _build_test_backup(self, duration: int) -> mxl.XMLBackup:
        backup = mxl.XMLBackup()
        backup.add_child(mxl.XMLDuration(value_=duration))
        return backup

    def _read_note_voice(self, note: mxl.XMLNote) -> str:
        voices = note.get_children_of_type(mxl.XMLVoice)
        self.assertGreater(len(voices), 0)
        return str(voices[0].value_)
