# ruff: noqa: S101

import unittest
import xml.etree.ElementTree as ET
from fractions import Fraction
from typing import Any

from homr.bar_placement import (
    AFTER_SHORTEST,
    EARLIEST_END,
    BarPlacement,
    after_shortest_adds_up,
    after_shortest_advance,
    after_shortest_is_closer,
    staff_ends,
)
from homr.music_xml_generator import (
    SymbolChord,
    XmlGeneratorArguments,
    _lone_rest_ids,
    add_tuplet_start_stop,
    generate_xml,
    group_into_chords,
)
from homr.transformer.vocabulary import EncodedSymbol
from homr.visual_sidecar.timing_repairs import TimingRepairs
from tests.test_timing_repairs import (
    CLEAN_BAR,
    EIGHTH_OVER_16TH,
    StubbedSidecar,
    butterfly_bar,
)
from training.transformer.training_vocabulary import read_token_lines

GRAND_STAFF_IN_A = [
    "clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower",
    "keySignature_3 . . . . .",
    "timeSignature/4 . . . . .",
]


def corridors_bar(sixteenth: str) -> list[str]:
    """Bar 33 of Chrono Trigger's Corridors of Time: a whole-note chord held over a bass
    arpeggio in eighths, under which a lower voice plays a dotted eighth and a 16th. The
    transformer reads the bar like this, but with the 16th as ``sixteenth``."""
    return [
        "note_1 F4 _ _ _ upper&note_1 C4 _ _ _ upper&note_1 A3 _ _ _ upper"
        + "&note_8 D3 _ _ _ lower&note_8. D2 _ _ _ lower",
        "note_8 F3 _ _ _ lower",
        f"{sixteenth} D2 _ _ _ lower",
        "note_8 B3 _ _ _ lower&rest_8 _ _ _ _ lower",
        "note_8 C4 _ _ _ upper&note_8 D2 _ _ _ lower",
        "note_8 F4 _ _ _ upper&note_4 D2 _ _ _ lower",
        "note_8 F3 _ _ _ lower",
        "note_8 B3 _ _ _ lower&note_8 A2 _ _ _ lower",
        "note_8 C4 _ _ _ lower&note_8 D3 _ _ _ lower",
        "barline . . . . .",
    ]


#: Bar 33 as printed, in quarter notes: what the earliest-end rule makes of the right tokens.
PRINTED_ONSETS = sorted(
    [
        ("1", "F4", 0.0),
        ("1", "C4", 0.0),
        ("1", "A3", 0.0),
        ("1", "C4", 1.5),
        ("1", "F4", 2.0),
        ("2", "D3", 0.0),
        ("2", "D2", 0.0),
        ("2", "F3", 0.5),
        ("2", "D2", 0.75),
        ("2", "B3", 1.0),
        ("2", "rest", 1.0),
        ("2", "D2", 1.5),
        ("2", "D2", 2.0),
        ("2", "F3", 2.5),
        ("2", "B3", 3.0),
        ("2", "A2", 3.0),
        ("2", "C4", 3.5),
        ("2", "D3", 3.5),
    ]
)

#: Bar 33 with the 16th read as a 32nd, each group starting after the shortest note of the
#: group before: the misread only moves the notes after it an eighth of a beat.
SHIFTED_ONSETS = sorted(
    [
        ("1", "F4", 0.0),
        ("1", "C4", 0.0),
        ("1", "A3", 0.0),
        ("1", "C4", 1.625),
        ("1", "F4", 2.125),
        ("2", "D3", 0.0),
        ("2", "D2", 0.0),
        ("2", "F3", 0.5),
        ("2", "D2", 1.0),
        ("2", "B3", 1.125),
        ("2", "rest", 1.125),
        ("2", "D2", 1.625),
        ("2", "D2", 2.125),
        ("2", "F3", 2.625),
        ("2", "B3", 3.125),
        ("2", "A2", 3.125),
        ("2", "C4", 3.625),
        ("2", "D3", 3.625),
    ]
)

#: Bar 25 of Corridors of Time as the transformer reads it: bar 33's misread under a
#: five-note chord, with the second half of the arpeggio written on the treble staff.
CORRIDORS_BAR_25 = [
    "note_8. D2 _ _ _ lower&note_8 D3 _ _ _ lower&note_1 G5 # _ _ upper&note_1 G4 # _ _ upper"
    + "&note_1 C5 # _ _ upper&note_1 A5 _ arpeggiate _ upper&note_1 A4 _ _ _ upper",
    "note_8 F3 # _ _ lower",
    "note_32 D2 _ staccato _ lower",
    "rest_8 _ _ _ _ lower&note_8 B3 _ _ _ lower",
    "note_8 D2 _ _ slurStart lower&note_8 C4 # _ _ upper",
    "note_8 F4 # _ _ upper&note_4 D2 _ _ slurStop lower",
    "note_8 F3 # _ _ upper",
    "note_8 B3 _ _ _ upper&note_8 A2 _ _ _ lower",
    "note_8 D3 _ _ _ lower&note_8 C4 # _ _ upper",
    "barline . . . . .",
]

#: Bar 25 with each group starting after the shortest note of the group before.
BAR_25_SHIFTED_ONSETS = sorted(
    [
        *[("1", pitch, 0.0) for pitch in ("G5", "G4", "C5", "A5", "A4")],
        ("1", "C4", 1.625),
        ("1", "F4", 2.125),
        ("1", "F3", 2.625),
        ("1", "B3", 3.125),
        ("1", "C4", 3.625),
        ("2", "D2", 0.0),
        ("2", "D3", 0.0),
        ("2", "F3", 0.5),
        ("2", "D2", 1.0),
        ("2", "rest", 1.125),
        ("2", "B3", 1.125),
        ("2", "D2", 1.625),
        ("2", "D2", 2.125),
        ("2", "A2", 3.125),
        ("2", "D3", 3.625),
    ]
)


def write(lines: list[str]) -> Any:
    return generate_xml(XmlGeneratorArguments(), [read_token_lines(lines)], "")


def _measures(xml: Any) -> list[ET.Element]:
    root = ET.fromstring(xml.to_string())  # noqa: S314 - generated by the test itself
    part = root.find("part")
    assert part is not None
    return part.findall("measure")


def _divisions(xml: Any) -> int:
    return int(_measures(xml)[0].findtext("attributes/divisions", "1"))


def _timed_notes(xml: Any, index: int) -> list[tuple[str, str, Fraction, Fraction]]:
    """(staff, pitch, onset, duration) in quarter notes for every note of one measure."""
    divisions = _divisions(xml)
    time, onset, result = 0, 0, []
    for element in _measures(xml)[index]:
        if element.tag == "backup":
            time -= int(element.findtext("duration", "0"))
        elif element.tag == "forward":
            time += int(element.findtext("duration", "0"))
        elif element.tag == "note":
            duration = int(element.findtext("duration", "0"))
            if element.find("chord") is None:
                onset = time
                time += duration
            pitch = element.find("pitch")
            name = (
                "rest"
                if pitch is None
                else pitch.findtext("step", "") + pitch.findtext("octave", "")
            )
            result.append(
                (
                    element.findtext("staff", "1"),
                    name,
                    Fraction(onset, divisions),
                    Fraction(duration, divisions),
                )
            )
    return result


def onsets(xml: Any, index: int = 0) -> list[tuple[str, str, float]]:
    return sorted((s, n, float(o)) for s, n, o, _ in _timed_notes(xml, index))


def written_bar_length(xml: Any) -> Fraction:
    """The bar length of the time signature the writer wrote, in whole notes."""
    beats = _measures(xml)[0].findtext("attributes/time/beats")
    beat_type = _measures(xml)[0].findtext("attributes/time/beat-type")
    assert beats is not None and beat_type is not None
    return Fraction(int(beats), int(beat_type))


def written_staff_ends(xml: Any, index: int = 0) -> dict[str, Fraction]:
    """When each staff's last note ends in one written measure, in whole notes."""
    ends: dict[str, Fraction] = {}
    for staff, _, onset, duration in _timed_notes(xml, index):
        key = "upper" if staff == "1" else "lower"
        ends[key] = max(ends.get(key, Fraction(0)), (onset + duration) / 4)
    return ends


def bars_of(lines: list[str]) -> tuple[list[SymbolChord], list[list[SymbolChord]], set[int]]:
    """The writer's groups for these tokens, the groups of each bar, and the lone rests."""
    groups = add_tuplet_start_stop(group_into_chords(read_token_lines(lines)))
    bars: list[list[SymbolChord]] = [[]]
    for group in groups:
        if group.is_barline():
            bars.append([])
        else:
            bars[-1].append(group)
    return groups, bars, _lone_rest_ids(groups)


def first_timed_group(groups: list[SymbolChord]) -> int:
    return next(i for i, g in enumerate(groups) if g.symbols[0].rhythm.startswith("note"))


class NoRepairs:
    """Timing repairs with nothing applied, or with lost notes in the given groups."""

    def __init__(self, repaired: list[SymbolChord] | None = None) -> None:
        self.repaired = [id(group.symbols[0]) for group in repaired or []]

    def lost_note_lengths(self, group: SymbolChord) -> list[Fraction]:
        return [Fraction(1, 16)] if id(group.symbols[0]) in self.repaired else []


class TestBarPlacement(unittest.TestCase):
    def test_a_misread_that_would_rush_the_bar_moves_the_rest_a_little_instead(self) -> None:
        """
        With the 16th read as a 32nd, starting groups when the earliest note ends puts the
        next group off the beat; each later group then starts at whichever of two ends comes
        first, so the bass rushes and stops at beat 2.5 while the chord holds to 4. Starting
        each group after the shortest note before it leaves every staff closer to the bar's
        end, so the bar is written that way: the notes after the misread start an eighth of a
        beat late and keep their spacing.
        """
        xml = write([*GRAND_STAFF_IN_A, *corridors_bar("note_32")])
        self.assertEqual(onsets(xml), SHIFTED_ONSETS)

    def test_a_bar_the_earliest_end_places_right_is_written_that_way(self) -> None:
        xml = write([*GRAND_STAFF_IN_A, *corridors_bar("note_16")])
        self.assertEqual(onsets(xml), PRINTED_ONSETS)

    def test_each_bar_is_placed_by_its_own_rule(self) -> None:
        xml = write([*GRAND_STAFF_IN_A, *corridors_bar("note_32"), *corridors_bar("note_16")])
        self.assertEqual(onsets(xml, 0), SHIFTED_ONSETS)
        self.assertEqual(onsets(xml, 1), PRINTED_ONSETS)

    def test_the_misread_bar_rushes_by_the_earliest_end(self) -> None:
        """What the fallback avoids: the earliest-end placement of the misread bar."""
        _, bars, lone = bars_of([*GRAND_STAFF_IN_A, *corridors_bar("note_32")])
        bar = Fraction(1)
        earliest_end = staff_ends(bars[0], EARLIEST_END, bar, lone)
        after_shortest = staff_ends(bars[0], AFTER_SHORTEST, bar, lone)
        self.assertEqual(earliest_end, {"upper": Fraction(1), "lower": Fraction(5, 8)})
        self.assertEqual(after_shortest, {"upper": Fraction(1), "lower": Fraction(33, 32)})
        self.assertTrue(after_shortest_is_closer(earliest_end, after_shortest, bar))

    def test_closer_means_every_staff_at_least_as_close_and_one_closer(self) -> None:
        bar = Fraction(1)
        earliest = {"upper": Fraction(1), "lower": Fraction(1, 2)}
        cases = [
            ({"upper": Fraction(1), "lower": Fraction(1, 2)}, False),  # the same
            ({"upper": Fraction(1), "lower": Fraction(3, 4)}, True),  # one closer
            ({"upper": Fraction(9, 8), "lower": Fraction(1)}, False),  # one farther
            ({"upper": Fraction(1), "lower": Fraction(5, 4)}, True),  # over by less than short
            ({"upper": Fraction(1), "lower": Fraction(3, 2)}, False),  # over by as much
            ({"upper": Fraction(1)}, False),  # different staves
        ]
        for after_shortest, closer in cases:
            with self.subTest(after_shortest=after_shortest):
                self.assertEqual(after_shortest_is_closer(earliest, after_shortest, bar), closer)
        both_closer = {"upper": Fraction(7, 8), "lower": Fraction(1, 4)}
        self.assertTrue(after_shortest_is_closer(both_closer, {"upper": bar, "lower": bar}, bar))
        self.assertFalse(after_shortest_is_closer({}, {}, bar))

    def test_a_rushed_bar_whose_shift_ends_a_staff_just_past_the_barline_is_shifted(
        self,
    ) -> None:
        """
        Bar 25 has bar 33's misread, but the second half of its arpeggio is on the treble
        staff. Starting groups after the shortest note then ends the treble an eighth of a
        beat past the barline instead of on it, so that placement is not closer on every
        staff. It does end both staves within an eighth note of the barline, where the
        earliest-end placement stops the bass a beat and a half short, so the bar is written
        after the shortest note.
        """
        _, bars, lone = bars_of([*GRAND_STAFF_IN_A, *CORRIDORS_BAR_25])
        bar = Fraction(1)
        earliest_end = staff_ends(bars[0], EARLIEST_END, bar, lone)
        after_shortest = staff_ends(bars[0], AFTER_SHORTEST, bar, lone)
        self.assertEqual(earliest_end, {"upper": Fraction(1), "lower": Fraction(5, 8)})
        self.assertEqual(after_shortest, {"upper": Fraction(33, 32), "lower": Fraction(33, 32)})
        self.assertFalse(after_shortest_is_closer(earliest_end, after_shortest, bar))
        self.assertTrue(after_shortest_adds_up(earliest_end, after_shortest, bar))
        xml = write([*GRAND_STAFF_IN_A, *CORRIDORS_BAR_25])
        self.assertEqual(onsets(xml), BAR_25_SHIFTED_ONSETS)

    def test_adding_up_means_every_staff_within_an_eighth_where_the_earliest_end_is_not(
        self,
    ) -> None:
        bar = Fraction(1)
        rushed = {"upper": Fraction(1), "lower": Fraction(5, 8)}
        nearly = {"upper": Fraction(1), "lower": Fraction(29, 32)}
        cases = [
            (
                "both just past",
                rushed,
                {"upper": Fraction(33, 32), "lower": Fraction(33, 32)},
                True,
            ),
            ("just short", rushed, nearly, True),
            ("an eighth past", rushed, {"upper": Fraction(9, 8), "lower": Fraction(1)}, False),
            ("an eighth short", rushed, {"upper": Fraction(1), "lower": Fraction(7, 8)}, False),
            ("earliest end adds up", nearly, {"upper": Fraction(33, 32), "lower": bar}, False),
            ("different staves", rushed, {"upper": bar}, False),
            ("nothing measured", {}, {}, False),
        ]
        for name, earliest_end, after_shortest, adds_up in cases:
            with self.subTest(case=name):
                self.assertEqual(after_shortest_adds_up(earliest_end, after_shortest, bar), adds_up)

    def test_without_a_bar_length_the_earliest_end_is_kept(self) -> None:
        groups, _, lone = bars_of([*GRAND_STAFF_IN_A, *corridors_bar("note_32")])
        first = first_timed_group(groups)
        repairs: Any = NoRepairs()
        self.assertEqual(BarPlacement(groups, lone, repairs).rule(first, None), EARLIEST_END)
        self.assertEqual(
            BarPlacement(groups, lone, repairs).rule(first, Fraction(1)), AFTER_SHORTEST
        )

    def test_a_bar_with_an_applied_shared_notehead_repair_keeps_the_earliest_end(self) -> None:
        """The repair says when the notes after a shared head start, by the earliest end."""
        groups, bars, lone = bars_of([*GRAND_STAFF_IN_A, *corridors_bar("note_32")])
        first = first_timed_group(groups)
        repaired: Any = NoRepairs([bars[0][-1]])
        self.assertEqual(
            BarPlacement(groups, lone, repaired).rule(first, Fraction(1)), EARLIEST_END
        )
        unrepaired: Any = NoRepairs()
        self.assertEqual(
            BarPlacement(groups, lone, unrepaired).rule(first, Fraction(1)), AFTER_SHORTEST
        )

    def test_lost_note_lengths_are_the_applied_repairs_and_record_nothing(self) -> None:
        lines = [
            "clef_G2 _ _ _ _ upper&clef_F4 _ _ _ _ lower",
            "keySignature_0 . . . . .",
            "timeSignature/4 . . . . .",
            *butterfly_bar("B4", "D5"),
            *CLEAN_BAR,
        ]
        sidecar = StubbedSidecar({"B4": EIGHTH_OVER_16TH, "D5": EIGHTH_OVER_16TH})
        groups = add_tuplet_start_stop(group_into_chords(read_token_lines(lines)))
        repairs = TimingRepairs(groups, sidecar)
        lengths = [repairs.lost_note_lengths(group) for group in groups]
        self.assertEqual(
            [
                [s.pitch for s in group.symbols if s.position == "upper"]
                for group, found in zip(groups, lengths, strict=True)
                if found
            ],
            [["B4"], ["D5"]],
        )
        self.assertEqual([found for found in lengths if found], [[Fraction(1, 16)]] * 2)
        self.assertEqual(sidecar.state.shared_notehead_records, [])

    def test_grace_notes_and_rests_in_the_shortest_note(self) -> None:
        def chord(*rhythms: str) -> SymbolChord:
            return SymbolChord([EncodedSymbol(r, "C4", position="upper") for r in rhythms])

        self.assertEqual(after_shortest_advance(chord("note_4", "note_8G")), Fraction(1, 4))
        self.assertEqual(after_shortest_advance(chord("note_8G")), Fraction(0))
        self.assertEqual(after_shortest_advance(chord("note_2", "rest_8")), Fraction(1, 8))
        self.assertEqual(after_shortest_advance(chord("note_12", "note_4")), Fraction(1, 12))

    def test_the_bar_is_measured_as_the_writer_writes_it(self) -> None:
        """The rule is chosen by where each staff ends; that must be where it ends written."""
        bars = {
            "misread 32nd": corridors_bar("note_32"),
            "printed 16th": corridors_bar("note_16"),
            "lone rest": [
                "note_4 C5 _ _ _ upper&rest_2 _ _ _ _ lower",
                "note_4 D5 _ _ _ upper",
                "note_2 E5 _ _ _ upper",
                "barline . . . . .",
            ],
            "lone rest read later": [
                "note_4 C5 _ _ _ upper",
                "note_4 D5 _ _ _ upper&rest_2 _ _ _ _ lower",
                "note_2 E5 _ _ _ upper",
                "barline . . . . .",
            ],
            "grace note and triplets": [
                "note_4 C5 _ _ _ upper&note_2 C3 _ _ _ lower",
                "note_8G D5 _ _ _ upper",
                "note_12 E5 _ _ _ upper",
                "note_12 F5 _ _ _ upper",
                "note_12 G5 _ _ _ upper",
                "note_2 F5 _ _ _ upper&note_2 G2 _ _ _ lower",
                "barline . . . . .",
            ],
            # The writer reads a group led by something other than a note or rest as that
            # symbol, and does not write the notes chorded with it.
            "note under a time signature": [
                "note_4 C5 _ _ _ upper&note_4 C3 _ _ _ lower",
                "timeSignature/4 . . . . .&note_4 E3 _ _ _ lower",
                "note_4 D5 _ _ _ upper&note_8 E3 _ _ _ lower",
                "note_2 E5 _ _ _ upper&note_2 G3 _ _ _ lower",
                "barline . . . . .",
            ],
        }
        multirest = ["rest_2m _ _ _ _ upper", "barline . . . . ."]
        for name, bar in bars.items():
            with self.subTest(bar=name):
                lines = [*GRAND_STAFF_IN_A, *bar, *multirest]
                xml = write(lines)
                groups, measured, lone = bars_of(lines)
                bar_length = written_bar_length(xml)
                placement = BarPlacement(groups, lone, NoRepairs())  # type: ignore[arg-type]
                rule = placement.rule(first_timed_group(groups), bar_length)
                self.assertEqual(
                    staff_ends(measured[0], rule, bar_length, lone), written_staff_ends(xml)
                )
                self.assertEqual(staff_ends(measured[1], rule, bar_length, lone), {})
